# Generated by Django 4.0.6 on 2022-09-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='cat',
        ),
    ]
