# Generated by Django 4.0.6 on 2022-09-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_category_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category', verbose_name='Категория'),
        ),
    ]
